Added note in Preferences section
mozilla/policy-templates pull request #704
Opened 2020-10-26 13:32 UTC by lucamanga

Added note in Preferences section, to remove settings in the old Preferences section otherwise it will not work

2020-11-02 21:35 UTC, mkaply requested changes

2020-11-02 21:35 UTC, mkaply commented on README.md
> +| **[`Preferences`](#preferences)** | Set and lock preferences. (NOTE: in order to use this, settings in the **[`Preferences (Deprecated)`](#preferences-deprecated)** section must be cleared.
Can you remove this one? They actually do mix and match everywhere except the GPO.

So I want to add a comment in the GPO itself.

2020-11-02 21:35 UTC, mkaply commented on README.md
> +**NOTE** In order to use this policy, you must clear all settings in the old **Preferences (Deprecated)** section.
Can you make this GPO/Windows specific? In order to use this policy on Windows.

Thanks!

2020-11-03 07:39 UTC, lucamanga reviewed
Made edit as your suggestion, @mkaply

2020-11-05 20:44 UTC, merged

2020-11-05 20:44 UTC, mkaply commented
Thanks!

2020-11-05 21:08 UTC, mkaply commented
I made the changes in each ADMX.

https://github.com/mozilla/policy-templates/commit/3c123e54a10662848d105e0df2d639efb7138430