German translations for printing dialog
mozilla/policy-templates pull request #923
Opened 2022-07-01 13:21 UTC by vossni

2022-07-01 19:06 UTC, htcfreek requested changes

2022-07-01 19:06 UTC, htcfreek commented on windows/de-DE/firefox.adml
> +      <string id="UseSystemPrintDialog">Systemseitigen Druckdialog verwenden</string>
```suggestion
      <string id="UseSystemPrintDialog">Systemdruckdialog verwenden</string>
```

2022-07-02 18:11 UTC, closed without merging

2022-07-02 18:12 UTC, vossni commented
Better translations in another pull request

2022-07-02 18:34 UTC, htcfreek commented
Why did you opened a new PR instead of creating a new commit here?